### ISSUE TITLE
Unable to Connect Using Connect-AzureRMAccount

### ISSUE THREAD

**Issue by gesbeckj** [microsoft/Partner-Center-PowerShell#134]
We are unable to connect using the Secure Application Model. Specifically the final step, Connect-AzureRMAccount fails with the error (Connect-AzureRmAccount : Exception has been thrown by the target of an invocation.) We are following the documented steps at https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5 and https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-1.5. We are able to successfully generate all of the tokens and authenticate with AzureAD, the Partner Center and MSOLOnline. The only issue we are having is with connecting to AzureRM. 

A deeper trace of the error reveals the following:
Message        : Exception has been thrown by the target of an invocation.
StackTrace     :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateCustomArmClient[TClient](Object[] parameters)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription(IAccessToken accessToken, IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, IAzureSubscription& subscription, IAzureTenant& tenant)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Reflection.TargetInvocationException
InvocationInfo : {Connect-AzureRmAccount}
Line           : Connect-AzureRmAccount -AccessToken $azureToken.AccessToken -GraphAccessToken $graphToken -TenantId $tenantID -AccountId $UID
Position       : At line:1 char:1
                 + Connect-AzureRmAccount -AccessToken $azureToken.AccessToken -GraphAcc ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 60

Message        : Attempted to access an element as a type incompatible with the array.
StackTrace     :    at System.Collections.Generic.List`1.Add(T item)
                    at Microsoft.Azure.Internal.Subscriptions.SubscriptionClient.Initialize()
                    at Microsoft.Azure.Internal.Subscriptions.SubscriptionClient..ctor(Uri baseUri, ServiceClientCredentials credentials, DelegatingHandler[] handlers)
Exception      : System.ArrayTypeMismatchException
InvocationInfo : {Connect-AzureRmAccount}
Line           : Connect-AzureRmAccount -AccessToken $azureToken.AccessToken -GraphAccessToken $graphToken -TenantId $tenantID -AccountId $UID
Position       : At line:1 char:1
                 + Connect-AzureRmAccount -AccessToken $azureToken.AccessToken -GraphAcc ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 60

**Comment by isaiahwilliams** [comment]
@gesbeckj what version of the AzureRM module are you using? That module has recently updated to a new version of the Microsoft.Rest.ClientRuntime library. You should be able to resolve this issue by updating to the latest version. Please let us know if this helps.

**Comment by gesbeckj** [comment]
Using 6.13.1 for AzureRM. which I believe is the latest version. I attempted to run Update-Module -Name AzureRM which did not update the version.

**Comment by isaiahwilliams** [comment]
@gesbeckj can you confirm that you have version 5.8.3 of the [AzureRM.Profile](https://www.powershellgallery.com/packages/AzureRM.profile/5.8.3) module installed?

**Comment by isaiahwilliams** [comment]
Please us know if you are still having issues connecting. Additional information about connecting can be found at at https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0
