### ISSUE TITLE
Get-PartnerCustomerSubscriptionUtilization error on some subscriptions only

### ISSUE THREAD

**Issue by jackkur** [Microsoft/Partner-Center-PowerShell#27]
# Steps to reproduce

`Connect-PartnerCenter -ApplicationId <GUID> -Credential $credential`

`$usage = Get-PartnerCustomerSubscriptionUtilization -CustomerId <GUID> -SubscriptionId <GUID> -StartDate <Date> -EndDate <Date> -Granularity Daily -ShowDetails`

## Expected behavior

Data from same subscriptions is retrieved properly with PartnerCenterModule 0.10.0.5

## Actual behavior

Error is returned by PartnerCenter 1.5.1810.2 for two subscriptions out of 16. Data for other 14 subscriptions is correct.

`System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Store.PartnerCenter.PowerShell.Common.ResourceExtensions.CopyFrom(PSAzureUtilizationRecord azureUtilizationRecord, AzureUtilizationRecord other) in D:\a\1\s\src\PowerShell\Common\ResourceExtensions.cs:line 56
at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerSubscriptionUtilization.<>c.<ExecuteCmdlet>b__24_0(AzureUtilizationRecord r) in D:\a\1\s\src\PowerShell\Commands\GetPartnerCustomerSubscriptionUtilization.cs:line 94
at System.Linq.Enumerable.WhereSelectListIterator``2.MoveNext()
at System.Collections.Generic.List``1.InsertRange(Int32 index, IEnumerable``1 collection)
at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerSubscriptionUtilization.ExecuteCmdlet() in D:\a\1\s\src\PowerShell\Commands\GetPartnerCustomerSubscriptionUtilization.cs:line 94
at Microsoft.Store.PartnerCenter.PowerShell.Commands.PartnerPSCmdlet.ProcessRecord() in D:\a\1\s\src\PowerShell\Commands\PartnerPSCmdlet.cs:line 61
at System.Management.Automation.CommandProcessor.ProcessRecord()
`

## Environment
Windows 10 Version 1803
PowerShell 5.1.17134.228
PartnerCenter 1.5.1810.2

**Comment by isaiahwilliams** [comment]
Hi @jackkur, 

I just published version [1.5.1810.4](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1810.4), it includes some modifications to the way the models are converted. Can you test this update and let me know if you are still having issues?

**Comment by jackkur** [comment]
> 
> 
> Hi @jackkur,
> 
> I just published version [1.5.1810.4](https://www.powershellgallery.com/packages/PartnerCenter/1.5.1810.4), it includes some modifications to the way the models are converted. Can you test this update and let me know if you are still having issues?

Hi @isaiahwilliams, 

Thank you so much for getting this fixed so quickly.
It is now working as expected.

Thank you,
Jack

**Comment by isaiahwilliams** [comment]
Hi @jackkur, 

That is great to hear! Please let us know if you have any other issue.
