### ISSUE TITLE
Exception calling Get-PartnerInvoice

### ISSUE THREAD

**Issue by alainfrickerisource** [microsoft/Partner-Center-PowerShell#308]
## Steps to reproduce
# Function Get-PartnerInvoice return an exception (it works until February 2020)
$datestart = get-date
Import-Module -Name 'C:\Program Files\WindowsPowerShell\Modules\PartnerCenter\1.5.1902.4\PartnerCenter'
$AppCred = New-Object System.Management.Automation.PSCredential $AppID, (ConvertTo-SecureString -String "$AppSecret" -AsPlainText -Force)
$pcToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -Credential $AppCred -TenantId $TenantId

Try {
    $connection = Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationId $AppID -TenantId $TenantId
} Catch {
    throw " `r`n $($datestart) - Unable to connect to the Microsoft Partner Center: `r`n $_.Exception.Message"
    Break
}

$pcPSInvoices = Get-PartnerInvoice

## Expected behavior
# Collection of invoices

## Actual behavior
At C:\scripts\getCspMicrosoftPartnerCenterInvoices.ps1:50 char:21
+     $pcPSInvoices = Get-PartnerInvoice
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PartnerInvoice], PartnerPSException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Exceptions.PartnerPSException,Microsoft.Store.P
   artnerCenter.PowerShell.Commands.GetPartnerInvoice

## Diagnostic logs
write-output $connection
# returns (after Connect-PartnerCenter)
Account            : Microsoft.Store.PartnerCenter.PowerShell.Authentication.AzureAccount
ApplicationId      : 1af7e388-75ff-4565-a64c-152da49fd6c3
AuthenticationType : AppPlusUser
CountryCode        : CH
Environment        : GlobalCloud
Locale             : de-CH

## Environment
Windows Server 2012 R2
PowerShell 5.1.14409.1005
.NET 4.7.03062

**Comment by isaiahwilliams** [comment]
@alainfrickerisource thank you for opening this issue. Can you run this again and after the error happens can you run `Resolve-PartnerError` then provide the output from that?

**Comment by alainfrickerisource** [comment]
@isaiahwilliams thank you for your input. Interesting ServerResponse: Forbidden

Here the response of Resolve-PartnerError:
Get-PartnerInvoice : Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown.
At C:\scripts\getCspMicrosoftPartnerCenterInvoices.ps1:53 char:21
+     $pcPSInvoices = Get-PartnerInvoice
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-PartnerInvoice], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerInvoice


CorrelationId    : dc5a600f-1b22-4d5c-8722-7293b1b13de5
Locale           : en-US
RequestId        : 64278b22-e94a-4bb3-869f-02b84451ee3d
RequestMessage   : {GET https://api.partnercenter.microsoft.com/v1/invoices}
ServerMessage    :
ServerResponse   : {Forbidden}
Exception        : Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Exception of type
                   'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown.
                      at
                   Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<HandleResponseAsync>d__38`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__24`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__21`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.Invoices.InvoiceCollectionOperations.<GetAsync>d__10.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerInvoice.<<ExecuteCmdlet>b__4_0>d.M
                   oveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.PowerShell.Utilities.ConcurrencyTaskScheduler.<RunConcurrentTask
                   Async>d__21.MoveNext()
HelpLink         :
Message          : Exception of type 'Microsoft.Store.PartnerCenter.Exceptions.PartnerException' was thrown.
StackTrace       :    at
                   Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<HandleResponseAsync>d__38`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__24`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.Network.PartnerServiceClient.<GetAsync>d__21`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.Invoices.InvoiceCollectionOperations.<GetAsync>d__10.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerInvoice.<<ExecuteCmdlet>b__4_0>d.M
                   oveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Store.PartnerCenter.PowerShell.Utilities.ConcurrencyTaskScheduler.<RunConcurrentTask
                   Async>d__21.MoveNext()
ErrorCategory    : CloseError: (:) [Get-PartnerInvoice], PartnerException
ErrorDetails     :
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, C:\scripts\getCspMicrosoftPartnerCenterInvoices.ps1: line 53

**Comment by isaiahwilliams** [comment]
@alainfrickerisource based on the information you have shared the credentials you are using do not have access to that feature. Can you confirm that you have a direct bill enrollment or that you are indirect provider? The reason I am asking is that indirect resellers will not have access to the Partner Center API, so that could be the other cause for this issue. 

I would recommend trying this operation using credentials that have admin agent privileges to rule out any permissions issue, if you have an enrollment into the Cloud Solution Provider program that has access to the Partner Center API.

**Comment by isaiahwilliams** [comment]
@alainfrickerisource reading back through this thread, I believe that you might be an encountering this issue due to your refresh token expiring. If you connect using 

```powershell
Connect-PartnerCenter
```

Does the get command work as you expect?

**Comment by alainfrickerisource** [comment]
Refresh token and Connect-Partner-Center works. Looks like credentials don't have access anymore. Strange this solution with same accounts worked already for years. Now the exception is 2700 lines.

**Comment by isaiahwilliams** [comment]
Based on your latest update it appears that your credentials no longer have access to Partner Center. Once those privileges are established, again, you should be able to use that account with this module to perform Partner Center operations.
