### ISSUE TITLE
Cannot retrieve usage data when running on the billing date

### ISSUE THREAD

**Issue by jackkur** [Microsoft/Partner-Center-PowerShell#50]
When running the following command today, which falls on the last day of billing cycle date, I get an exception. It worked fine when running on any other day (when today in UTC < $EndTime).

Get-PartnerCustomerSubscriptionUtilization -CustomerId $CustomerId -SubscriptionId $SubscriptionId -StartDate $StartTime -EndDate $EndTime -Granularity Daily -ShowDetails

Get-PartnerCustomerSubscriptionUtilization: Value cannot be null.
Parameter name: resourceCollection
   at Microsoft.Store.PartnerCenter.Enumerators.BaseResourceCollectionEnumerator`1..ctor(IPartner rootPartnerOperations, T resourceCollection, JsonConverter resourceCollectionConverter)
   at Microsoft.Store.PartnerCenter.Factory.IndexBasedCollectionEnumeratorFactory`2.Create(TResourceCollection resourceCollection)
   at Microsoft.Store.PartnerCenter.PowerShell.Commands.GetPartnerCustomerSubscriptionUtilization.ExecuteCmdlet()
   at Microsoft.Store.PartnerCenter.PowerShell.Commands.PartnerPSCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by jackkur** [comment]
I have executed the script today and it worked correctly with no errors.
This issue happens exactly one day every month on the billing date.

**Comment by isaiahwilliams** [comment]
Hi @jackkur, 

Thank you for sharing this information with us. I have seen this behavior in a few circumstances, but they were caused by using none UTC times. Can you share how you are specifying the start and end date parameters?

**Comment by jackkur** [comment]
Hi @isaiahwilliams,
I pass start and end dates in System.DateTime variables.
For example: 
$StartTime = (Get-Date -Year 2019 -Month 1 -Day 14 -Hour 0 -Minute 0 -Second 0 -Millisecond 0)
Year, Month and Day are calculated based on invoices. The time is always set to "00:00:00 -8". (Pacific Time Zone).
Example of range executed today without any issues:
12/14/2018 00:00:00 - 01/14/2019 00:00:00
When I will run this exact same range on Jan 13th after 4PM PST (Jan 14th 00:00 UTC), it will error out as described above. My billing date is the 14th.
Executing it 24h later will work again.

I hope this helps.

Thank you,
Jack

**Comment by jackkur** [comment]
Hi @isaiahwilliams ,
The problem occurs only when there is no usage data yet for selected period. I modified my script to skip the date range starting on the billing day and instead pull that range a day later.

The error message has changed recently and it is more descriptive:
Get-PartnerCustomerSubscriptionUtilization: Microsoft.Store.PartnerCenter.PowerShell.Exceptions.PartnerPSException: 2000 reported_start_time has to be before reported_end_time at Microsoft.Store.PartnerCenter.PowerShell.Commands.PartnerPSCmdlet.ProcessRecord() at System.Management.Automation.CommandProcessor.ProcessRecord()

I think this ticket can be closed.
Thank you,
Jack
