### ISSUE TITLE
New-PartnerCustomer does not work - Bad Request

### ISSUE THREAD

**Issue by cblackuk** [Microsoft/Partner-Center-PowerShell#7]
# Steps to reproduce

```powershell
New-PartnerCustomer -BillingAddressLine1 '1 Microsoft Way' -BillingAddressCity 'Redmond' -BillingAddressCountry 'US' -BillingAddressPostalCode '98052' -BillingAddressState 'WA' -ContactEmail 'jdoe@customer.com' -ContactFirstName 'Jane' -ContactLastName 'Doe' -Culture 'en-US' -Domain 'domaintestname.onmicrosoft.com' -Language 'en' -Name 'New CustomerTest'
New-PartnerCustomer : Bad Request
At line:1 char:1
+ New-PartnerCustomer -BillingAddressLine1 '1 Microsoft Way' -BillingAd ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerCustomer], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerCustomer

```
## Environment

```powershell
Get-Module -Name PartnerCenter

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0.1808.2 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserRoleMember, Connect-PartnerCenter, Get-PartnerAgreementDetail...}
```

**Comment by cblackuk** [comment]
Not sure if this is the first part of the process based on https://docs.microsoft.com/en-us/azure/cloud-solution-provider/customer-management/create-new-customer#powershell

But I expeced it to create a new user and no matter what params I put it just does Bad Request and nothing happens...

**Comment by cblackuk** [comment]
More debug log:
```powershell
ErrorRecord                 : Bad Request
WasThrownFromThrowStatement : False
Message                     : Bad Request
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : Partner Exception:
                              Error Category: BadInput
                              Service Error Payload: null
                              Context: Request Id: 5af9144e-33f8-4ce2-b12f-cff14a37e56a, Correlation Id: c3f652a0-e779-4dc7-b744-95f44d177311, Locale: en-US
                              Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: Bad Request
                                 at Microsoft.Store.PartnerCenter.PartnerService.SynchronousExecute[T](Func`1 operation)
                                 at Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerCustomer.ExecuteCmdlet()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()

TargetSite                  : Void Throw()
StackTrace                  :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                 at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                              commandRedirections, FunctionContext funcContext)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
HelpLink                    :
Source                      : mscorlib
HResult                     : -2146233087
```

**Comment by cblackuk** [comment]
I figured it out! I know what is wrong and how to fix it! I also have an improvement for your code to make it obvious for other people, will create a PR for the improvement tomorrow morning!!!

**Comment by isaiahwilliams** [comment]
Hi @cblackuk 

This issue was closed when I merged the pull request. I am working to publish an update that will make the error message more visible. This update should be available later this week. Thank you for digging into this issue.

**Comment by cblackuk** [comment]
Hi @isaiahwilliams  thanks for that :-) there is a syntax issue in my PR ;-( I was literally fixing it but you just merged it
